# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('owner', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('business', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=100)),
                ('expire_date', models.CharField(max_length=20)),
                ('is_void', models.BooleanField(default=0)),
            ],
        ),
    ]
