# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='coupon',
            name='exp_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='url_code',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Business'),
        ),
    ]
