# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160712_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Business'),
        ),
    ]
