# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160721_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='exp_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
