# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20160721_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='about',
        ),
    ]
