# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20160726_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.FileField(blank=True, upload_to='logo/'),
        ),
    ]
