# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20160728_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
