# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20160729_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='exp_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
