# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20160729_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
