# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20160730_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
