# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20160820_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='view_time',
            field=models.DateTimeField(),
        ),
    ]
