# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20160820_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='view',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
