# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 02:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20160820_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='view_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
