# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20160821_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
